OTA-2653 Move "Getting Started Page
advancedtelematic/ats-garage-docs pull request #84
Opened 2019-05-07 14:04 UTC by merltron

We have to move the getting started page from the web app to the docs site. I thought the intro page would be a good place for it since this is true "end-to-end" getting started content.

The web app is running out of space so we can no longer host a dedicated "Getting Started" page there. See the parent case for more details on the proposed UI changes.

2019-05-07 15:29 UTC, tkfu requested changes
I think it's important to replace the screenshots with ones that don't show features that aren't available to the general public. Because they'll need to be redone for that purpose anyway, let's also fix the images so that they aren't PNG embedded in SVG.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +1.  Open the OTA Connect Portal, open the menu for your user profile and click *Provisioning Keys*
This should be a link.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +image:../images/s1-prov.svg[image]
This is a general comment for all the images: why are they SVG files with low-res PNG data embedded inside in base64?

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +image:../images/s2-find.svg[image]
This screenshot is from the demo account, and has fake dashboard features. For the docs, we should be using the real, current UI.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +* Navigate to the *Devices* page and select the *All Devices* or *Ungrouped Devices* menu items.
Again, can be linked directly.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +1.  Open the *Devices* tab and click *+Add group*.
Devices tab can be linked.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +1.  Open the device details that we first looked at in === Step 3
Should be an anchor link. You can do it by linking to a slugified version of the section title, but best practice is to actually assign an ID, and then use either the bare xref syntax or the custom link text:

```
[#group-devices]
=== Step 3: Group Your Devices

You can follow <<group-devices>> to <<group-devices,learn to add devices to groups>>.
```

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +2.  Navigate to **Devices**, select a device group, and select a test device within that group.
Devices tab can be directly linked.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +When you create a software update, you need to define two basic „assignment criteria“.
Don't use German smart quotes.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +That step is covered when you create a *Campaign* which we‘ll get to next...
Missing a comma.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +* In the second step of our Getting Started guide, we showed you how to create a smart group.
I believe this was the 3rd step. This is why it's good to use the x-ref syntax.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +1.  To upload some software, follow these steps:
Feels wrong for step 1 of a process to be "follow these steps". This sentence should probably be outside of the ordered list.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +** For more information about this method, see the https://docs.ota.here.com/quickstarts/start-intro.html[developer documentation].
Remove one of the asterisks--it's not rendering properly right now.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +.
Looks like you added the newline before the period instead of after.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +** *Programming Sequencer* – Configure the sequence in which each piece of software is installed. You can also configure some rollback behavior in case any piece of software failed to install.
Again, we shouldn't put demo features that aren't actually available in the docs.

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +* If your campaign is a test campaign, it might finish quickly, in which case, you‘ll find it on the *Finished* tab
Missing period

2019-05-07 15:29 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +5.  Click the blacklist icon image:../images/ban_grey.png[Icon] next to the version number.
Image renders gigantic--please set height/width attributes.

2019-05-08 09:36 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +image:../images/s2-find.svg[image]
@tkfu  Sorry, I don't follow - what are the fake features you see? I just compared this page in "real" and "demo" and they look pretty much the same (apart from the devices listed).

2019-05-08 09:39 UTC, tkfu commented on _posts/2018-02-08-start-intro.adoc
> +image:../images/s2-find.svg[image]
The bottom section with the charts. They show features (like cert monitoring and forecasting connection numbers) that aren't yet implemented.

2019-05-08 12:52 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +* If your campaign is a test campaign, it might finish quickly, in which case, you‘ll find it on the *Finished* tab
fixed

2019-05-08 12:52 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +** *Programming Sequencer* – Configure the sequence in which each piece of software is installed. You can also configure some rollback behavior in case any piece of software failed to install.
fixed

2019-05-08 12:52 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +.
fixed

2019-05-08 12:52 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +** For more information about this method, see the https://docs.ota.here.com/quickstarts/start-intro.html[developer documentation].
fixed

2019-05-08 12:53 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +image:../images/s2-find.svg[image]
ahh.  I realize the confusion now. I was using Benes account which I thought was "normal" and comparing it to the "demo" account which is "demo". In reality, both accounts have demo features enabled. I created a login for myself and the alpha features are gone.

2019-05-08 12:54 UTC, merltron commented on _posts/2018-02-08-start-intro.adoc
> +image:../images/s2-find.svg[image]
fixed

2019-05-08 12:57 UTC, merltron commented
@tkfu OK I think I fixed everything - have another look and let me know if it's OK:

2019-05-08 13:55 UTC, tkfu approved these changes
I added a minor fix-up commit (13bb3a1), and squashed the image editing commits. I'm happy with this as-is; might be a good idea to double-check 13bb3a1 before merging.

2019-05-08 14:27 UTC, merged

2019-05-08 14:28 UTC, merltron commented
Thanks - 13bb3a1 looks fine.